export { default as factors } from "./factors";
export { default as isAntiprime } from "./isAntiprime";
export { default as isAntiprimeCandidate } from "./isAntiprimeCandidate";
export { default as isConsecutivePrimeFactors } from "./isConsecutivePrimeFactors";
export { default as isHighlyComposite } from "./isAntiprime";
export { default as isPrime } from "./isPrime";
export { default as isPrimeExponentsReducing } from "./isPrimeExponentsReducing";
export { default as nextPrime } from "./nextPrime";
export { default as primeFactors } from "./primeFactors";
